blogicum/blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/<int:id>/', views.post_detail, name='post_detail'),
    path('category/<slug:category_slug>/', views.category_posts, name='category_posts'),
    path('add_post/', views.add_post, name='add_post'),
    path('login/', views.login_view, name='login'),
    path('registration/', views.registration_view, name='registration'),
    path('logout/', views.logout_view, name='logout'),
    path('post/<int:id>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:id>/delete/', views.post_delete, name='post_delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogicum/blogicum/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls')),
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
]

blogicum/templates/includes/category_link.html
<a class="text-muted" href="{% url 'blog:category_posts' post.category.slug %}">
  «{{ post.category.title }}»
</a>

blogicum/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© Блогикум</p>    
</footer>

blogicum/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'blog:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Блогикум
      </a>
      {% with request.resolver_match.view_name as view_name %}        
        <ul class="nav  nav-pills">
          <li class="nav-item">              
            <a class="nav-link {% if view_name == 'blog:index' %} active {% endif %}" href="{% url 'blog:index' %}">
              Лента записей
            </a>
          </li>
          <li class="nav-item">              
            <a class="nav-link {% if view_name == 'pages:about' %} active {% endif %}" href="{% url 'pages:about' %}">
              О проекте
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'pages:rules' %} active {% endif %}" href="{% url 'pages:rules' %}">
              Наши правила
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'blog:add_post' %} active {% endif %}" href="{% url 'blog:add_post' %}">
              Добавить пост
            </a>
          </li>
        </ul>
      {% endwith %}      
    </div>
  </nav> 
</header>

blogicum/templates/includes/paginator.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_other_pages %}
      <nav class="nav justify-content-center">
      <ul class="pagination">
      {% if page.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
        </li>
      {% else %}
        <li class="page-item disabled">
        <span class="page-link">&laquo; Предыдущая</span>
        </li>
      {% endif %}
      {% for i in page.paginator.page_range %}
        {% if page.number == i %}
          <li class="page-item active">
          <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page.has_next %}
        <li class="page-item">
        <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
        </li>
      {% else %}
        <li class="page-item disabled">
        <span class="page-link">Следующая &raquo;</span>
        </li>
      {% endif %}
      </ul>
      </nav>
    {% endif %}
    </span>
</div>

blogicum/templates/includes/post_card.html
<div class="card" style="width: 40rem;">
  <div class="card-body">
    <h5 class="card-title">{{ post.title }}</h5>
    <h6 class="card-subtitle mb-2 text-muted">
      <small>
        {{ post.pub_date|date:"d E Y" }} | {% if post.location and post.location.is_published %}{{ post.location.name }}{% else %}Планета Земля{% endif %}<br>
        От автора @{{ post.author.username }} в категории {% include "includes/category_link.html" %}
      </small>
    </h6>
    <p class="card-text">{{ post.text|truncatewords:10 }}</p>
    {% if post.image %}
      <img src="{{ post.image.url }}" alt="Изображение поста" style="width: 100px; height: 100px; object-fit: cover;">
      <br>
    {% endif %}
    <a href="{% url 'blog:post_detail' post.id %}" class="card-link">Читать полный текст</a>
  </div>
</div>