blogicum/blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/<int:id>/', views.post_detail, name='post_detail'),
    path('category/<slug:category_slug>/', views.category_posts, name='category_posts'),
    path('add_post/', views.add_post, name='add_post'),
    path('login/', views.login_view, name='login'),
    path('registration/', views.registration_view, name='registration'),
    path('logout/', views.logout_view, name='logout'),
    path('post/<int:id>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:id>/delete/', views.post_delete, name='post_delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogicum/blogicum/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls')),
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
]

blogicum/blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.files.images import get_image_dimensions
from PIL import Image as PILImage
from django.core.exceptions import ValidationError

User = get_user_model()

class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создание')
    class Meta:
        abstract = True
        
class Category (BaseModel):
    title = models.CharField(max_length=256, verbose_name='Заголовок')
    description = models.TextField(verbose_name='Описание')
    slug = models.SlugField(unique=True, verbose_name='Идентификатор', help_text='Идентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано', help_text="Снимите галочку, чтобы скрыть публикацию.")
    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'Категории'
        
    def __str__(self):
        return self.title
    
class Location (BaseModel):
    name = models.CharField(max_length=256, verbose_name='Название места')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано', help_text="Введите своё имя")
    class Meta:
        verbose_name = 'местоположение'
        verbose_name_plural = 'Местоположения'
        
    def __str__(self):
        return self.name
    
class Post (BaseModel):
    title = models.CharField(max_length=256, verbose_name='Заголовок')
    text = models.TextField(verbose_name='Текст')
    pub_date = models.DateTimeField(verbose_name='Дата и время публикации', help_text='Если установить дату и время в будущем — можно делать отложенные публикации.')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор публикации')
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null = True, verbose_name='Местоположение')
    category = models.ForeignKey("Category", on_delete=models.SET_NULL, null = True, verbose_name='Категория')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано', help_text="Введите своё имя")
    image = models.ImageField(upload_to='images', null = True, blank=True)
    class Meta:
        verbose_name = 'публикация'
        verbose_name_plural = 'Публикации'
    
    def __str__(self):
        return self.title
    def delete_image(self):
        if self.image:
            self.image.delete(save=False)
            self.image = None
            self.save()
    
    def clean(self):
        if not self.title:
            raise ValidationError('Заголовок не может быть пустым')
        if not self.text:
            raise ValidationError('Текст не может быть пустым')
        if not self.category:
            raise ValidationError('Категория не может быть пустой')
        if not self.location:
            raise ValidationError('Местоположение не может быть пустым')

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

blogicum/blog/forms.py
from django import forms
from .models import Post
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

User = get_user_model()



class LoginForm(forms.Form):
    username = forms.CharField(label='Логин', max_length=255)
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)

class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text', 'category', 'location', 'image')

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super().save(commit=False)
        print(self.user)
        if self.user:
            instance.author = self.user
        instance.pub_date = timezone.now()
        if commit:
            instance.save()
        return instance
    
class PostEditForm(PostForm):
    class Meta:
        model = Post
        fields = ('title', 'text', 'image', 'category', 'location')
    

blogicum/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.utils import timezone
from django.core.paginator import Paginator
from blog.models import Post, Category
from django.shortcuts import render, redirect
from .forms import PostForm, PostEditForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from .forms import LoginForm, RegistrationForm

now = timezone.now()
paginator_pages = 5

def index(request):
    template_name = 'blog/index.html'
    postsbd = Post.objects.filter(
        pub_date__lte=now,
        is_published=True,
        category__is_published=True
    ).order_by('-pub_date')
    paginator = Paginator(postsbd, paginator_pages)
    page = paginator.get_page(request.GET.get('page'))
    context = {'page': page}
    return render(request, template_name, context)

def post_detail(request, id):
    template_name = 'blog/detail.html'
    post = get_object_or_404(Post, id=id)
    if post.pub_date > timezone.now():
        raise Http404("Публикация еще не доступна.")
    elif not post.is_published:
        raise Http404("Публикация не найдена или не опубликована.")
    elif not post.category.is_published:
        raise Http404("Категория публикации не найдена или не опубликована.")
    context = {'post': post}
    return render(request, template_name, context)


def category_posts(request, category_slug):
    template_name = 'blog/category.html'
    category = get_object_or_404(Category, slug=category_slug)
    if not category.is_published:
        raise Http404("Категория не найдена или не опубликована.")
    postsbd = Post.objects.filter(
        category=category,
        pub_date__lte=now,
        is_published=True,
        )
    context = {
        'postsbd': postsbd,
        'category': category,  
    }
    return render(request, template_name, context)



def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('blog:index')
    else:
        form = LoginForm()
    return render(request, 'blog/login.html', {'form': form})

def registration_view(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:login')
    else:
        form = RegistrationForm()
    return render(request, 'blog/registration.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('blog:index')



def add_post(request):
    if not request.user.is_authenticated:
        return redirect('blog:login')
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, user=request.user)
        form.request = request
        if form.is_valid():
            form.save()
            return redirect('blog:index')
    else:
        form = PostForm()
    return render(request, 'blog/add_post.html', {'form': form})

@login_required
def post_edit(request, id):
    post = get_object_or_404(Post, id=id)
    if post.author != request.user:
        return redirect('blog:index')
    if request.method == 'POST':
        form = PostEditForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('blog:post_detail', id=id)
    else:
        form = PostEditForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

@login_required
def post_delete(request, id):
    post = get_object_or_404(Post, id=id)
    if post.author != request.user:
        return redirect('blog:index')
    if request.method == 'POST':
        post.delete()
        return redirect('blog:index')
    return redirect('blog:index')

blogicum/templates/blog/add_post.html
{% extends 'base.html' %}

{% block content %}
  <h1>Добавить пост</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Добавить</button>
  </form>
{% endblock %}

blogicum/templates/blog/category.html
{% extends "base.html" %}
{% block title %}
  Публикации в категории «{{ category.title }}»
{% endblock %}
{% block content %}
<h1>Публикации в категории «{{ category.title }}»</h1>
<p class="mb-5">{{ category.description }}</p>
{% for post in postsbd %}
  <article class="mb-5">  
    {% include "includes/post_card.html" %}
  </article>   
{% endfor %}

{% endblock %}

blogicum/templates/blog/detail.html
{% extends "base.html" %}
{% block title %}
{{ post.title }} | {% if post.location and post.location.is_published %}{{ post.location.name }} |{% endif %} {{ post.pub_date|date:"d E Y" }}
{% endblock %}
{% block content %}
  <article>
    <p>{{ post.pub_date|date:"d E Y" }} | {% if post.location and post.location.is_published %}{{ post.location.name }}{% else %}Планета Земля{% endif %}<br>
      <small>От автора @{{ post.author.username }} в категории {% include "includes/category_link.html" %}</small></p>
    <h3>{{ post.title }}</h3>
    <p>{{ post.text|linebreaksbr }}</p>
    {% if post.image %}
      <img src="{{ post.image.url }}" alt="{{ post.title }}" width="800" height="600">
    {% endif %}
  </article> 
  {% if user.is_authenticated and user == post.author %}
  <a href="{% url 'blog:post_edit' post.id %}" class="btn btn-primary">Редактировать пост</a>
  <form method="post" action="{% url 'blog:post_delete' post.id %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Удалить пост</button>
  </form>
  {% endif %}
{% endblock %}

blogicum/templates/blog/index.html
{% extends "base.html" %}
{% block title %}
  Лента записей
{% endblock %}
{% block content %}
  <h1 class="mb-5">Лента записей</h1>
  {% for post in page %}
    <article class="mb-5">  
      {% include "includes/post_card.html" %}
    </article>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

blogicum/templates/blog/login.html
{% extends 'base.html' %}

{% block content %}
  <h1>Вход</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Войти</button>
  </form>
{% endblock %}

blogicum/templates/blog/post_edit.html
{% extends "base.html" %}

{% block title %}
  Редактирование поста
{% endblock %}

{% block content %}
  <h1>Редактирование поста</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
  </form>
{% endblock %}

blogicum/templates/blog/registration.html
{% extends 'base.html' %}

{% block content %}
  <h1>Регистрация</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Зарегистрироваться</button>
  </form>
{% endblock %}